<?php

$now = time();
$expiration = $now + 100;

$expiration_seconds = $expiration - $now;
$expiration_date = gmdate( 'D, d M Y H:i:s',  $expiration ).' GMT';

header( 'Expires: '.$expiration_date);
header( 'Cache-Control: public,max-age='.$expiration_seconds );

?>
<html>
<body>
The time is: <?php echo gmdate( 'D, d M Y H:i:s' ); ?> at this very moment.<br /><br /><br />
<p><i><b>Seinfeld</b></i> is an American <a href="/wiki/Sitcom" title="Sitcom">sitcom</a> that originally ran for nine seasons on <a href="/wiki/NBC" title="NBC">NBC</a>, from 1989 to 1998. It was created by <a href="/wiki/Larry_David" title="Larry David">Larry David</a> and <a href="/wiki/Jerry_Seinfeld" title="Jerry Seinfeld">Jerry Seinfeld</a>, the latter starring as <a href="/wiki/Jerry_Seinfeld_(character)" title="Jerry Seinfeld (character)">a fictionalized version of himself</a>. Set predominantly in an apartment building in <a href="/wiki/Manhattan" title="Manhattan">Manhattan</a>'s <a href="/wiki/Upper_West_Side" title="Upper West Side">Upper West Side</a> in New York City (although taped entirely in Los Angeles), the show features a handful of Jerry's friends and acquaintances, particularly best friend <a href="/wiki/George_Costanza" title="George Costanza">George Costanza</a> (<a href="/wiki/Jason_Alexander" title="Jason Alexander">Jason Alexander</a>), former girlfriend <a href="/wiki/Elaine_Benes" title="Elaine Benes">Elaine Benes</a> (<a href="/wiki/Julia_Louis-Dreyfus" title="Julia Louis-Dreyfus">Julia Louis-Dreyfus</a>), and neighbor across the hall <a href="/wiki/Cosmo_Kramer" title="Cosmo Kramer">Cosmo Kramer</a> (<a href="/wiki/Michael_Richards" title="Michael Richards">Michael Richards</a>).</p>
<p><i>Seinfeld</i> was produced by <a href="/wiki/Castle_Rock_Entertainment" title="Castle Rock Entertainment">Castle Rock Entertainment</a>. In syndication the series has been distributed by <a href="/wiki/Sony_Pictures_Television" title="Sony Pictures Television">Sony Pictures Television</a> since 2002. It was largely written by David and Seinfeld with script writers who included <a href="/wiki/Larry_Charles" title="Larry Charles">Larry Charles</a>, <a href="/wiki/Peter_Mehlman" title="Peter Mehlman">Peter Mehlman</a>, <a href="/wiki/Gregg_Kavet" title="Gregg Kavet">Gregg Kavet</a>, <a href="/w/index.php?title=Andy_Robin&amp;action=edit&amp;redlink=1" class="new" title="Andy Robin (page does not exist)">Andy Robin</a>, <a href="/wiki/Carol_Leifer" title="Carol Leifer">Carol Leifer</a>, <a href="/wiki/David_Mandel" title="David Mandel">David Mandel</a>, <a href="/wiki/Jeff_Schaffer" title="Jeff Schaffer">Jeff Schaffer</a>, <a href="/wiki/Steve_Koren" title="Steve Koren">Steve Koren</a>, <a href="/wiki/Jennifer_Crittenden" title="Jennifer Crittenden">Jennifer Crittenden</a>, <a href="/wiki/Tom_Gammill_and_Max_Pross" title="Tom Gammill and Max Pross">Tom Gammill</a>, <a href="/wiki/Tom_Gammill_and_Max_Pross" title="Tom Gammill and Max Pross">Max Pross</a>, <a href="/wiki/Dan_O%27Keefe_(writer)" title="Dan O'Keefe (writer)">Dan O'Keefe</a>, <a href="/wiki/Charlie_Rubin" title="Charlie Rubin">Charlie Rubin</a>, <a href="/wiki/Marjorie_Gross" title="Marjorie Gross">Marjorie Gross</a>, <a href="/wiki/Alec_Berg" title="Alec Berg">Alec Berg</a>, <a href="/wiki/Elaine_Pope" title="Elaine Pope">Elaine Pope</a>, and <a href="/wiki/Spike_Feresten" title="Spike Feresten">Spike Feresten</a>.</p>
<p>A favorite among critics, the series led the <a href="/wiki/Nielsen_ratings" title="Nielsen ratings">Nielsen ratings</a> in seasons six and nine, and finished among the top two (with NBC's <i><a href="/wiki/ER_(TV_series)" title="ER (TV series)">ER</a></i>) every year from 1994 to 1998. In 2002, <i><a href="/wiki/TV_Guide" title="TV Guide">TV Guide</a></i> named <i>Seinfeld</i> the <a href="/wiki/TV_Guide%27s_50_Greatest_TV_Shows_of_All_Time" title="TV Guide's 50 Greatest TV Shows of All Time">greatest television program of all time</a>.<sup id="cite_ref-tvguide_1-0" class="reference"><a href="#cite_note-tvguide-1">[1]</a></sup> In 1997, the episodes "<a href="/wiki/The_Boyfriend_(Seinfeld)" title="The Boyfriend (Seinfeld)">The Boyfriend</a>" and "<a href="/wiki/The_Parking_Garage" title="The Parking Garage">The Parking Garage</a>" were respectively ranked numbers 4 and 33 on <i>TV Guide'</i>s <a href="/wiki/100_Greatest_Episodes_of_All_Time" title="100 Greatest Episodes of All Time" class="mw-redirect">100 Greatest Episodes of All Time</a>,<sup id="cite_ref-2" class="reference"><a href="#cite_note-2">[2]</a></sup> and in 2009, "<a href="/wiki/The_Contest" title="The Contest">The Contest</a>" was ranked #1 on the same magazine's list of TV's Top 100 Episodes of All Time.<sup id="cite_ref-TVGuide100Episodes_3-0" class="reference"><a href="#cite_note-TVGuide100Episodes-3">[3]</a></sup> <a href="/wiki/E!" title="E!">E!</a> named it the "number 1 reason the '90s ruled."<sup id="cite_ref-e-101_4-0" class="reference"><a href="#cite_note-e-101-4">[4]</a></sup> In 2013, the <a href="/wiki/Writers_Guild_of_America" title="Writers Guild of America">Writers Guild of America</a> named <i>Seinfeld</i> the No. 2 Best Written TV Series of All Time (second to <i><a href="/wiki/The_Sopranos" title="The Sopranos">The Sopranos</a></i>).<sup id="cite_ref-writers_guild_of_america_5-0" class="reference"><a href="#cite_note-writers_guild_of_america-5">[5]</a></sup> That same year, <i><a href="/wiki/Entertainment_Weekly" title="Entertainment Weekly">Entertainment Weekly</a></i> named it the No. 3 best TV series of all time<sup id="cite_ref-6" class="reference"><a href="#cite_note-6">[6]</a></sup> and TV Guide ranked it at No. 2.<sup id="cite_ref-auto_7-0" class="reference"><a href="#cite_note-auto-7">[7]</a></sup></p>
<p></p>
<div id="toc" class="toc">
<div id="toctitle">
<h2>Contents</h2>
</div>
<ul>
<li class="toclevel-1 tocsection-1"><a href="#Premise"><span class="tocnumber">1</span> <span class="toctext">Premise</span></a>
<ul>
<li class="toclevel-2 tocsection-2"><a href="#Characters"><span class="tocnumber">1.1</span> <span class="toctext">Characters</span></a></li>
<li class="toclevel-2 tocsection-3"><a href="#Plotlines"><span class="tocnumber">1.2</span> <span class="toctext">Plotlines</span></a></li>
<li class="toclevel-2 tocsection-4"><a href="#Themes"><span class="tocnumber">1.3</span> <span class="toctext">Themes</span></a></li>
<li class="toclevel-2 tocsection-5"><a href="#Catchphrases"><span class="tocnumber">1.4</span> <span class="toctext">Catchphrases</span></a></li>
<li class="toclevel-2 tocsection-6"><a href="#Music"><span class="tocnumber">1.5</span> <span class="toctext">Music</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-7"><a href="#Episodes"><span class="tocnumber">2</span> <span class="toctext">Episodes</span></a>
<ul>
<li class="toclevel-2 tocsection-8"><a href="#Seasons_1.E2.80.933"><span class="tocnumber">2.1</span> <span class="toctext">Seasons 1–3</span></a></li>
<li class="toclevel-2 tocsection-9"><a href="#Seasons_4.E2.80.935"><span class="tocnumber">2.2</span> <span class="toctext">Seasons 4–5</span></a></li>
<li class="toclevel-2 tocsection-10"><a href="#Seasons_6.E2.80.937"><span class="tocnumber">2.3</span> <span class="toctext">Seasons 6–7</span></a></li>
<li class="toclevel-2 tocsection-11"><a href="#Seasons_8.E2.80.939"><span class="tocnumber">2.4</span> <span class="toctext">Seasons 8–9</span></a></li>
<li class="toclevel-2 tocsection-12"><a href="#Series_finale"><span class="tocnumber">2.5</span> <span class="toctext">Series finale</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-13"><a href="#Production"><span class="tocnumber">3</span> <span class="toctext">Production</span></a></li>
<li class="toclevel-1 tocsection-14"><a href="#High-definition_versions"><span class="tocnumber">4</span> <span class="toctext">High-definition versions</span></a></li>
<li class="toclevel-1 tocsection-15"><a href="#Reception_and_legacy"><span class="tocnumber">5</span> <span class="toctext">Reception and legacy</span></a>
<ul>
<li class="toclevel-2 tocsection-16"><a href="#U.S._television_ratings"><span class="tocnumber">5.1</span> <span class="toctext">U.S. television ratings</span></a></li>
<li class="toclevel-2 tocsection-17"><a href="#Awards_and_nominations"><span class="tocnumber">5.2</span> <span class="toctext">Awards and nominations</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-18"><a href="#Consumer_products"><span class="tocnumber">6</span> <span class="toctext">Consumer products</span></a></li>
<li class="toclevel-1 tocsection-19"><a href="#Home_video_releases"><span class="tocnumber">7</span> <span class="toctext">Home video releases</span></a>
<ul>
<li class="toclevel-2 tocsection-20"><a href="#DVD_releases"><span class="tocnumber">7.1</span> <span class="toctext">DVD releases</span></a></li>
<li class="toclevel-2 tocsection-21"><a href="#Streaming_on_Hulu"><span class="tocnumber">7.2</span> <span class="toctext">Streaming on Hulu</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-22"><a href="#After_Seinfeld"><span class="tocnumber">8</span> <span class="toctext">After <i>Seinfeld</i></span></a>
<ul>
<li class="toclevel-2 tocsection-23"><a href="#Another_scene"><span class="tocnumber">8.1</span> <span class="toctext">Another scene</span></a></li>
<li class="toclevel-2 tocsection-24"><a href="#The_Seinfeld_.22curse.22"><span class="tocnumber">8.2</span> <span class="toctext">The <i>Seinfeld</i> "curse"</span></a></li>
<li class="toclevel-2 tocsection-25"><a href="#Curb_Your_Enthusiasm"><span class="tocnumber">8.3</span> <span class="toctext"><i>Curb Your Enthusiasm</i></span></a></li>
<li class="toclevel-2 tocsection-26"><a href="#Comedians_in_Cars_Getting_Coffee"><span class="tocnumber">8.4</span> <span class="toctext"><i>Comedians in Cars Getting Coffee</i></span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-27"><a href="#References"><span class="tocnumber">9</span> <span class="toctext">References</span></a>
<ul>
<li class="toclevel-2 tocsection-28"><a href="#General_references"><span class="tocnumber">9.1</span> <span class="toctext">General references</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-29"><a href="#External_links"><span class="tocnumber">10</span> <span class="toctext">External links</span></a></li>
</ul>
</div>
<p></p>
<h2><span class="mw-headline" id="Premise">Premise</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Seinfeld&amp;action=edit&amp;section=1" title="Edit section: Premise">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
<h3><span class="mw-headline" id="Characters">Characters</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Seinfeld&amp;action=edit&amp;section=2" title="Edit section: Characters">edit</a><span class="mw-editsection-bracket">]</span></span></h3>
<dl>
<dt>Main</dt>
</dl>
<div class="thumb tright">
<div class="thumbinner" style="width:222px;"><a href="/wiki/File:Seinfeld_actors_montage.jpg" class="image"><img alt="" src="220px-Seinfeld_actors_montage.jpg" width="220" height="259" class="thumbimage" data-file-width="524" data-file-height="618" /></a>
<div class="thumbcaption">
<div class="magnify"><a href="/wiki/File:Seinfeld_actors_montage.jpg" class="internal" title="Enlarge"></a></div>
The main cast of <i>Seinfeld</i></div>
</div>
</div>
<ul>
<li><a href="/wiki/Jerry_Seinfeld_(character)" title="Jerry Seinfeld (character)">Jerry Seinfeld</a> (<a href="/wiki/Jerry_Seinfeld" title="Jerry Seinfeld">Jerry Seinfeld</a>) – Jerry is a "minor celebrity" stand-up comedian who is often portrayed as "the voice of reason" amidst the general insanity generated by the people in his world. The in-show character is a slight <a href="/wiki/Germaphobe" title="Germaphobe" class="mw-redirect">germaphobe</a> and <a href="/wiki/Compulsive_behavior" title="Compulsive behavior">neat freak</a>, as well as an avid <a href="/wiki/Superman" title="Superman">Superman</a>, <a href="/wiki/New_York_Mets" title="New York Mets">New York Mets</a> and breakfast cereal fan. Jerry's apartment is the center of a world visited by his eccentric friends and a focus of the show.<sup id="cite_ref-8" class="reference"><a href="#cite_note-8">[8]</a></sup> Plot lines often involve Jerry's social interactions and romantic relationships. He typically finds minute, finicky reasons to break up with women, including a habit of eating peas one at a time, over-sized "man hands", and an annoying laugh. Other plot lines involve his longtime nemesis <a href="/wiki/Newman_(Seinfeld)" title="Newman (Seinfeld)">Newman</a> and his overbearing relatives, with whom he meets periodically.</li>
<li><a href="/wiki/Elaine_Benes" title="Elaine Benes">Elaine Benes</a> (<a href="/wiki/Julia_Louis-Dreyfus" title="Julia Louis-Dreyfus">Julia Louis-Dreyfus</a>) – Elaine is Jerry's ex-girlfriend and later friend. She is attractive and assertive, while also being playful, selfish and occasionally self-righteous. She sometimes has a tendency to be too honest with people (usually by losing her temper), which often gets her into trouble.<sup id="cite_ref-9" class="reference"><a href="#cite_note-9">[9]</a></sup> She usually gets caught up in her boyfriends' quirks, her eccentric employers' unusual behaviors and idiosyncrasies, and the maladjustment of total strangers. She tends to make poor choices in men she chooses to date and is often overly reactionary. First she works at Pendant Publishing with Mr. Lippman, is later hired as a personal assistant for Mr. Pitt, and later works for the J. Peterman catalogue as a glorified assistant. One of Elaine's trademark moves is her forceful shove while exclaiming "Get Out!" when she receives good, objectionable or surprising news. Another is her memorable "<a href="/wiki/The_Little_Kicks" title="The Little Kicks">Little Kicks</a>" dance move, which is described as a full body heave accompanied by a double-fisted "thumbs-up" and, "little kicks." She hates <i><a href="/wiki/The_English_Patient_(Seinfeld_episode)" title="The English Patient (Seinfeld episode)" class="mw-redirect">The English Patient</a></i>, which is met with significant social disapproval. Elaine is popularly described as an amalgamation of David's and Seinfeld's girlfriends during their early days in New York as struggling comedians.</li>
<li><a href="/wiki/Cosmo_Kramer" title="Cosmo Kramer">Cosmo Kramer</a> (<a href="/wiki/Michael_Richards" title="Michael Richards">Michael Richards</a>) – Kramer is Jerry's "wacky neighbor". His trademarks include his humorous upright <a href="/wiki/Pompadour_hairstyle" title="Pompadour hairstyle" class="mw-redirect">pompadour hairstyle</a>, vintage clothing and energetic sliding bursts through Jerry's apartment door. The Cosmo Kramer character was heavily based on a neighbor of Larry David's during his amateur comedic years in Manhattan. At times, he appears naive, dense and infantile, and at others insightful, experienced and inexplicably influential; similarly, he is exaggeratedly successful, socially, with his charm and easygoing manner. This is seen in his infallible success with women and employers. He has been described as a "hipster doofus". Although he never holds a steady job, he is rarely short of money and often invents wacky schemes that often work at first then eventually fail. Among these are <a href="/wiki/Coffee_table_book" title="Coffee table book">coffee table books</a> about coffee tables (for which he appeared on <i><a href="/wiki/Live_with_Regis_and_Kathie_Lee" title="Live with Regis and Kathie Lee" class="mw-redirect">Live with Regis and Kathie Lee</a></i>) and a <a href="/wiki/Bra" title="Bra">bra</a> for men called the <i>Bro</i>, also known as the <i>Manssiere</i>, with <a href="/wiki/Frank_Costanza" title="Frank Costanza" class="mw-redirect">Frank Costanza</a>. Kramer is longtime friends with Newman, and they work well together despite their differences.<sup id="cite_ref-10" class="reference"><a href="#cite_note-10">[10]</a></sup></li>
<li><a href="/wiki/George_Costanza" title="George Costanza">George Costanza</a> (<a href="/wiki/Jason_Alexander" title="Jason Alexander">Jason Alexander</a>) – George is Jerry's best friend, and has been since high school. He is miserly, dishonest, petty and envious of others' achievements.<sup id="cite_ref-11" class="reference"><a href="#cite_note-11">[11]</a></sup> He is portrayed as a loser who is perpetually insecure about his capabilities. He complains and lies easily about his profession, relationships and almost everything else, which usually creates trouble for him later. He often uses the alias Art Vandelay when lying or concocting a cover story. Despite these shortcomings, George has a sense of loyalty to his friends, has success in dating women and eventually secures a successful career as Assistant to the Traveling Secretary for the <a href="/wiki/New_York_Yankees" title="New York Yankees">New York Yankees</a>. During the run of the show, George and Jerry work with NBC to produce a pilot episode of a TV show called <i>Jerry</i>. During this time, he meets Susan Ross, who works for NBC. George has an on-and-off relationship with her, eventually getting engaged, until she dies at the end of season seven.</li>
</ul>
<dl>
<dt>Recurring</dt>
</dl>
<div role="note" class="hatnote relarticle mainarticle">Main article: <a href="/wiki/List_of_Seinfeld_minor_characters" title="List of Seinfeld minor characters">List of Seinfeld minor characters</a></div>
<p>Many characters have made multiple appearances, such as Jerry's nemesis <a href="/wiki/Newman_(Seinfeld)" title="Newman (Seinfeld)">Newman</a> and his <a href="/wiki/Uncle_Leo" title="Uncle Leo">Uncle Leo</a>. In addition to recurring characters, <i>Seinfeld</i> features numerous celebrities who appear as themselves or as girlfriends, boyfriends, bosses and other acquaintances. Many actors who made guest appearances became household names later in their careers, or were already well known.</p>
<h3><span class="mw-headline" id="Plotlines">Plotlines</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Seinfeld&amp;action=edit&amp;section=3" title="Edit section: Plotlines">edit</a><span class="mw-editsection-bracket">]</span></span></h3>
<p>Many <i>Seinfeld</i> episodes are based on the writers' real-life experiences, with the experiences re-interpreted for the characters' storyline. For example, George's storyline, "<a href="/wiki/The_Revenge_(Seinfeld)" title="The Revenge (Seinfeld)">The Revenge</a>", is based on Larry David's experience at <i><a href="/wiki/Saturday_Night_Live" title="Saturday Night Live">Saturday Night Live</a></i>.<sup id="cite_ref-12" class="reference"><a href="#cite_note-12">[12]</a></sup> "<a href="/wiki/The_Contest" title="The Contest">The Contest</a>" is also based on David's experiences. "<a href="/wiki/The_Smelly_Car" title="The Smelly Car">The Smelly Car</a>" storyline is based on Peter Mehlman's lawyer friend, who could not get a bad smell out of his car. "<a href="/wiki/The_Strike_(Seinfeld)" title="The Strike (Seinfeld)">The Strike</a>" is based on Dan O'Keefe's dad, who made up his own holiday—<a href="/wiki/Festivus" title="Festivus">Festivus</a>.<sup id="cite_ref-13" class="reference"><a href="#cite_note-13">[13]</a></sup> Other stories take on a variety of turns. "<a href="/wiki/The_Chinese_Restaurant" title="The Chinese Restaurant">The Chinese Restaurant</a>" consists of the main characters (excluding Kramer) waiting for a table throughout the entire episode.<sup id="cite_ref-14" class="reference"><a href="#cite_note-14">[14]</a></sup> "<a href="/wiki/The_Boyfriend_(Seinfeld)" title="The Boyfriend (Seinfeld)">The Boyfriend</a>", revolving around <a href="/wiki/Keith_Hernandez" title="Keith Hernandez">Keith Hernandez</a>, extends through two episodes.<sup id="cite_ref-15" class="reference"><a href="#cite_note-15">[15]</a></sup> "<a href="/wiki/The_Betrayal_(Seinfeld)" title="The Betrayal (Seinfeld)" class="mw-redirect">The Betrayal</a>" is famous for using <a href="/wiki/Reverse_chronology" title="Reverse chronology">reverse chronology</a>, and was inspired by a similar plot device in a <a href="/wiki/Harold_Pinter" title="Harold Pinter">Harold Pinter</a> play, <a href="/wiki/Betrayal_(play)" title="Betrayal (play)"><i>Betrayal</i></a>.<sup id="cite_ref-16" class="reference"><a href="#cite_note-16">[16]</a></sup> Some stories were inspired by headlines and rumors, as explained in the DVD features "Notes About Nothing", "Inside Look", and "Audio Commentary." In "<a href="/wiki/The_Maestro_(Seinfeld)" title="The Maestro (Seinfeld)">The Maestro</a>", Kramer's lawsuit is roughly similar to the <a href="/wiki/Liebeck_v._McDonald%27s_Restaurants" title="Liebeck v. McDonald's Restaurants">McDonald's coffee case</a>.<sup id="cite_ref-17" class="reference"><a href="#cite_note-17">[17]</a></sup> "<a href="/wiki/The_Outing_(Seinfeld)" title="The Outing (Seinfeld)">The Outing</a>" is based primarily on rumors that Larry Charles heard about Jerry Seinfeld's sexuality.<sup id="cite_ref-18" class="reference"><a href="#cite_note-18">[18]</a></sup></p>
<h3><span class="mw-headline" id="Themes">Themes</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Seinfeld&amp;action=edit&amp;section=4" title="Edit section: Themes">edit</a><span class="mw-editsection-bracket">]</span></span></h3>
<p><i>Seinfeld</i> broke several conventions of <a href="/wiki/Mainstream" title="Mainstream">mainstream</a> television. It is often described as being "a show about nothing".<sup id="cite_ref-19" class="reference"><a href="#cite_note-19">[19]</a></sup><sup id="cite_ref-20" class="reference"><a href="#cite_note-20">[20]</a></sup> However, Seinfeld in 2014 stated "the pitch for the show, the real pitch, when Larry and I went to NBC in 1988, was we want to show how a comedian gets his material. The show about nothing was just a joke in an episode many years later, and Larry and I to this day are surprised that it caught on as a way that people describe the show, because to us it's the opposite of that."<sup id="cite_ref-21" class="reference"><a href="#cite_note-21">[21]</a></sup></p>
<p>It became the first television series since <i><a href="/wiki/Monty_Python%27s_Flying_Circus" title="Monty Python's Flying Circus">Monty Python's Flying Circus</a></i> to be widely described as <a href="/wiki/Postmodernism" title="Postmodernism">postmodern</a>.<sup id="cite_ref-grenz_22-0" class="reference"><a href="#cite_note-grenz-22">[22]</a></sup> Several elements of <i>Seinfeld</i> fit in with a postmodern interpretation.<sup id="cite_ref-baltimore_sun_23-0" class="reference"><a href="#cite_note-baltimore_sun-23">[23]</a></sup></p>
<p>The show is typically driven by humor interspersed with superficial conflict and characters with peculiar dispositions. Many episodes revolved around the characters' involvement in the lives of others with typically disastrous results. On the set, the notion that the characters should not develop or improve throughout the series was expressed as the "no hugging, no learning" rule.<sup id="cite_ref-baltimore_sun_23-1" class="reference"><a href="#cite_note-baltimore_sun-23">[23]</a></sup> Unlike most sitcoms, there are no moments of <a href="/wiki/Pathos" title="Pathos">pathos</a>; the audience is never made to feel sorry for any of the characters. Even <a href="/wiki/The_Invitations" title="The Invitations">Susan's death</a> elicits no genuine emotions from anyone in the show.<sup id="cite_ref-24" class="reference"><a href="#cite_note-24">[24]</a></sup></p>
<p>The characters are "thirty-something singles with vague identities, no roots, and conscious indifference to morals."<sup id="cite_ref-25" class="reference"><a href="#cite_note-25">[25]</a></sup> Usual conventions, such as isolating the characters from the actors playing them and separating the characters' world from that of the actors and audience, were broken. One such example is the <a href="/wiki/Story_arc" title="Story arc">story arc</a> in which the characters promote a television sitcom series named <i>Jerry</i>. The <a href="/wiki/Show_within_a_show" title="Show within a show" class="mw-redirect">show within a show</a>, <i>Jerry</i>, was much like <i>Seinfeld</i> in that it was "about nothing" and Seinfeld played himself. The fictional <i>Jerry</i> was launched in the season four finale, but unlike <i>Seinfeld</i>, it was not picked up as a series. <i>Jerry</i> is one of many examples of <a href="/wiki/Metafiction" title="Metafiction">metafiction</a> in the show. There are no fewer than 22 fictional movies featured, such as <i>Rochelle, Rochelle</i>.<sup id="cite_ref-26" class="reference"><a href="#cite_note-26">[26]</a></sup></p>
<h3><span class="mw-headline" id="Catchphrases">Catchphrases</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Seinfeld&amp;action=edit&amp;section=5" title="Edit section: Catchphrases">edit</a><span class="mw-editsection-bracket">]</span></span></h3>
<p>Many terms were coined, popularized, or re-popularized in the series' run and have become part of popular culture.<sup id="cite_ref-27" class="reference"><a href="#cite_note-27">[27]</a></sup><sup id="cite_ref-28" class="reference"><a href="#cite_note-28">[28]</a></sup> Notable catchphrases include "<a href="/wiki/The_Yada_Yada" title="The Yada Yada">Yada, yada, yada</a>", "<a href="/wiki/The_Soup_Nazi" title="The Soup Nazi">No soup for you</a>", "<a href="/wiki/The_Alternate_Side" title="The Alternate Side">These pretzels are making me thirsty</a>" and "<a href="/wiki/The_Outing_(Seinfeld)" title="The Outing (Seinfeld)">Not that there's anything wrong with that</a>".</p>
<p>Other popular terms that made the transition into <a href="/wiki/Slang" title="Slang">slang</a> were created by, directed at or about secondary characters, including: "<a href="/wiki/Festivus" title="Festivus">Festivus</a>", "<a href="/wiki/The_Sponge" title="The Sponge">spongeworthy</a>", "<a href="/wiki/Chips_and_dip#Double-dipping" title="Chips and dip">double-dipping</a>", and "<a href="/wiki/Regift" title="Regift">re-gifter</a>".</p>
<p>As a body, the lexicon of Seinfeldian code words and recurring phrases that evolved around particular episodes is referred to as <a href="/wiki/Seinlanguage" title="Seinlanguage">Seinlanguage</a>, the title of Jerry Seinfeld's best-selling book on humor.<sup id="cite_ref-grenz_22-1" class="reference"><a href="#cite_note-grenz-22">[22]</a></sup></p>
<h3><span class="mw-headline" id="Music">Music</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Seinfeld&amp;action=edit&amp;section=6" title="Edit section: Music">edit</a><span class="mw-editsection-bracket">]</span></span></h3>
<p>A signature of <i>Seinfeld</i> is its theme music. Composed by <a href="/wiki/Jonathan_Wolff_(musician)" title="Jonathan Wolff (musician)">Jonathan Wolff</a>, it consists of distinct solo <a href="/wiki/Sampling_(music)" title="Sampling (music)">sampled</a> bass <a href="/wiki/Synthesizer" title="Synthesizer">synthesizer</a> riffs (played on a <a href="/wiki/Korg_M1" title="Korg M1">Korg M1</a> synthesizer) which open the show and connect the scenes, often accompanied by a "percussion track" composed of mouth noises, such as pops and clicks.<sup id="cite_ref-29" class="reference"><a href="#cite_note-29">[29]</a></sup> The bass synthesizer music eventually replaced the original music by Jep Epstein when it was played again after the first broadcast "<a href="/wiki/The_Seinfeld_Chronicles" title="The Seinfeld Chronicles">The Seinfeld Chronicles</a>". The show lacked a traditional title track and the riffs were played over the first moments of dialogue or action. They vary throughout each episode and are played in an improvised funk style. An additional musical theme with an ensemble, led by a synthesized mid-range brass instrument, ends each episode.</p>
<p>In "<a href="/wiki/The_Note_(Seinfeld)" title="The Note (Seinfeld)">The Note</a>", the first episode of season three, the bumper music featured a <a href="/wiki/Scat_singing" title="Scat singing">scatting</a> female jazz vocalist who sang a phrase that sounded like "easy to beat". Jerry Seinfeld and executive producer Larry David both liked Wolff's additions, and three episodes were produced with this new style music. However, they had neglected to inform NBC and Castle Rock executives of the change, and when the season premiere aired, the executives were surprised and unimpressed, and requested that they return to the original style. The subsequent two episodes were redone, leaving this episode as the only one with additional music elements.<sup id="cite_ref-30" class="reference"><a href="#cite_note-30">[30]</a></sup> In the commentary of "The Note", Julia Louis-Dreyfus facetiously suggests it was removed because the perceived lyric related closely to the low ratings at the time.<sup id="cite_ref-31" class="reference"><a href="#cite_note-31">[31]</a></sup></p>
<p>In the final three seasons (7, 8 &amp; 9), the bits were tweaked slightly with more frenetic rhythms; a bass guitar was added in addition to the sampled bass from earlier seasons. Throughout the show, the main theme could be re-styled in different ways depending on the episode. For instance, in "The Betrayal", in which part of the episode takes place in India, the theme is heard played on a <a href="/wiki/Sitar" title="Sitar">sitar</a>.</p>
</body>
</html>