version: '2'

networks:
  local:
    driver: bridge

services:
  varnish:
    build: .
    image: mpwar/varnish
    ports:
      - "8001:8080"
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    networks:
      - local

  app:
    image: php:7.1-apache
    ports:
      - "8000:80"
    volumes:
      - ".:/var/www/html"
    networks:
      - local
